<a href="https://colab.research.google.com/github/msali64/ML-training/blob/main/Day_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 numpy:                      array operations,
 pandas:                     DAta manipulation and analysis,
 matplotlib and seaborn:     Graphical analysis,
 sklearn MAchine leanring:   algorithms and techniques,
 statsmodels:                Statistical analysis,
 scipy:                      statiscial analysis,

In [ ]:
import numpy as pd

In [ ]:
j=[4,45,5,6,7,5]
j

[4, 45, 5, 6, 7, 5]

In [ ]:
j=np.array(j)
j


array([ 4, 45,  5,  6,  7,  5])

In [ ]:
type(d)

numpy.ndarray

In [ ]:
tuple(j)

(4, 45, 5, 6, 7, 5)

In [ ]:
d

array([ 4, 45,  5,  6,  7,  5])

In [ ]:
d.shape

(6,)

In [ ]:
d.ndim

1

In [ ]:
d.size

6

In [ ]:
a = [[9, 3, 4, 5, 6, 7], [8, 4, 2, 2, 7, 8], [3, 4, 6, 7, 8, 8, 7], [3, 3, 5, 6, 78, 44, 2, 2]]
print(a)
print(type(a))

[[9, 3, 4, 5, 6, 7], [8, 4, 2, 2, 7, 8], [3, 4, 6, 7, 8, 8, 7], [3, 3, 5, 6, 78, 44, 2, 2]]
<class 'list'>


In [ ]:
a1 = np.array(a,dtype=object)
print(a1)
print(type(a1))

[list([9, 3, 4, 5, 6, 7]) list([8, 4, 2, 2, 7, 8])
 list([3, 4, 6, 7, 8, 8, 7]) list([3, 3, 5, 6, 78, 44, 2, 2])]
<class 'numpy.ndarray'>


In [ ]:
a1

array([list([9, 3, 4, 5, 6, 7]), list([8, 4, 2, 2, 7, 8]),
       list([3, 4, 6, 7, 8, 8, 7]), list([3, 3, 5, 6, 78, 44, 2, 2])],
      dtype=object)

In [ ]:
a1.shape

(4,)

In [ ]:
a1.size

4

In [ ]:
a1.ndim

1

In [ ]:
range(-10,1)

range(-10, 1)

In [ ]:
list(range(-10,1))

[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0]

In [ ]:
list(range(-10,1,2))

[-10, -8, -6, -4, -2, 0]

In [ ]:
list(range(-10,10,3)) # range allows only int

[-10, -7, -4, -1, 2, 5, 8]

In [ ]:
z=np.arange(-10,10,3)

In [ ]:
type(z)

numpy.ndarray

In [ ]:
z.size

7

In [ ]:
z.shape

(7,)

In [ ]:
z.ndim

1

In [ ]:
z

array([-10,  -7,  -4,  -1,   2,   5,   8])

In [ ]:
for i in range(5,55,5):
  print("KAKAKA",i)

KAKAKA 5
KAKAKA 10
KAKAKA 15
KAKAKA 20
KAKAKA 25
KAKAKA 30
KAKAKA 35
KAKAKA 40
KAKAKA 45
KAKAKA 50


In [ ]:
j=[5,87,23,46,62,84,80,45,77,33,80]

In [ ]:
j

[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]

In [ ]:
for i in range(0,len(j), 2):
    print(j[i])

5
23
62
80
77
80


In [ ]:
for i in range(1,len(j), 2):
    print(j[i])

87
46
84
45
33


In [ ]:
x=[]
y=[]
for i in range(len(j)):
  if i%2==0:
    x.append(j[i])
  else:
    y.append(j[i])

In [ ]:
print(x)
print(y)

[5, 23, 62, 80, 77, 80]
[87, 46, 84, 45, 33]


In [ ]:
range(1,10)

range(1, 10)

In [ ]:
for i in range(1,10):
  print(i)

1
2
3
4
5
6
7
8
9
